import { School, Sport } from "@/types";

export const BIG_TEN_SCHOOLS: School[] = [
  {
    id: "illinois",
    name: "Illinois",
    abbr: "ILL",
    slug: "illinois",
    city: "Champaign",
    state: "IL",
    primaryColor: "#E84A27",
    secondaryColor: "#13294B",
    espnId: 356,
    mascot: "Fighting Illini",
    domain: "illinois.edu",
  },
  {
    id: "indiana",
    name: "Indiana",
    abbr: "IU",
    slug: "indiana",
    city: "Bloomington",
    state: "IN",
    primaryColor: "#990000",
    secondaryColor: "#FFFFFF",
    espnId: 84,
    mascot: "Hoosiers",
    domain: "indiana.edu",
  },
  {
    id: "iowa",
    name: "Iowa",
    abbr: "IOWA",
    slug: "iowa",
    city: "Iowa City",
    state: "IA",
    primaryColor: "#FFCD00",
    secondaryColor: "#000000",
    espnId: 2294,
    mascot: "Hawkeyes",
    domain: "uiowa.edu",
  },
  {
    id: "maryland",
    name: "Maryland",
    abbr: "UMD",
    slug: "maryland",
    city: "College Park",
    state: "MD",
    primaryColor: "#E03A3E",
    secondaryColor: "#FFD520",
    espnId: 97,
    mascot: "Terrapins",
    domain: "umd.edu",
  },
  {
    id: "michigan",
    name: "Michigan",
    abbr: "MICH",
    slug: "michigan",
    city: "Ann Arbor",
    state: "MI",
    primaryColor: "#00274C",
    secondaryColor: "#FFCB05",
    espnId: 130,
    mascot: "Wolverines",
    domain: "umich.edu",
  },
  {
    id: "michigan-state",
    name: "Michigan State",
    abbr: "MSU",
    slug: "michigan-state",
    city: "East Lansing",
    state: "MI",
    primaryColor: "#18453B",
    secondaryColor: "#FFFFFF",
    espnId: 127,
    mascot: "Spartans",
    domain: "msu.edu",
  },
  {
    id: "minnesota",
    name: "Minnesota",
    abbr: "MINN",
    slug: "minnesota",
    city: "Minneapolis",
    state: "MN",
    primaryColor: "#7A0019",
    secondaryColor: "#FFCC33",
    espnId: 135,
    mascot: "Golden Gophers",
    domain: "umn.edu",
  },
  {
    id: "nebraska",
    name: "Nebraska",
    abbr: "NEB",
    slug: "nebraska",
    city: "Lincoln",
    state: "NE",
    primaryColor: "#E41C38",
    secondaryColor: "#F5F1E7",
    espnId: 158,
    mascot: "Cornhuskers",
    domain: "unl.edu",
  },
  {
    id: "northwestern",
    name: "Northwestern",
    abbr: "NU",
    slug: "northwestern",
    city: "Evanston",
    state: "IL",
    primaryColor: "#4E2A84",
    secondaryColor: "#FFFFFF",
    espnId: 77,
    mascot: "Wildcats",
    domain: "northwestern.edu",
  },
  {
    id: "ohio-state",
    name: "Ohio State",
    abbr: "OSU",
    slug: "ohio-state",
    city: "Columbus",
    state: "OH",
    primaryColor: "#BA0C2F",
    secondaryColor: "#A2AAAD",
    espnId: 194,
    mascot: "Buckeyes",
    domain: "osu.edu",
  },
  {
    id: "oregon",
    name: "Oregon",
    abbr: "ORE",
    slug: "oregon",
    city: "Eugene",
    state: "OR",
    primaryColor: "#154733",
    secondaryColor: "#FEE123",
    espnId: 2483,
    mascot: "Ducks",
    domain: "uoregon.edu",
  },
  {
    id: "penn-state",
    name: "Penn State",
    abbr: "PSU",
    slug: "penn-state",
    city: "University Park",
    state: "PA",
    primaryColor: "#041E42",
    secondaryColor: "#FFFFFF",
    espnId: 213,
    mascot: "Nittany Lions",
    domain: "psu.edu",
  },
  {
    id: "purdue",
    name: "Purdue",
    abbr: "PUR",
    slug: "purdue",
    city: "West Lafayette",
    state: "IN",
    primaryColor: "#CEB888",
    secondaryColor: "#000000",
    espnId: 2509,
    mascot: "Boilermakers",
    domain: "purdue.edu",
  },
  {
    id: "rutgers",
    name: "Rutgers",
    abbr: "RU",
    slug: "rutgers",
    city: "Piscataway",
    state: "NJ",
    primaryColor: "#CC0033",
    secondaryColor: "#5F6A72",
    espnId: 164,
    mascot: "Scarlet Knights",
    domain: "rutgers.edu",
  },
  {
    id: "ucla",
    name: "UCLA",
    abbr: "UCLA",
    slug: "ucla",
    city: "Los Angeles",
    state: "CA",
    primaryColor: "#2D68C4",
    secondaryColor: "#F2A900",
    espnId: 26,
    mascot: "Bruins",
    domain: "ucla.edu",
  },
  {
    id: "usc",
    name: "USC",
    abbr: "USC",
    slug: "usc",
    city: "Los Angeles",
    state: "CA",
    primaryColor: "#990000",
    secondaryColor: "#FFC72C",
    espnId: 30,
    mascot: "Trojans",
    domain: "usc.edu",
  },
  {
    id: "washington",
    name: "Washington",
    abbr: "WASH",
    slug: "washington",
    city: "Seattle",
    state: "WA",
    primaryColor: "#4B2E83",
    secondaryColor: "#B7A57A",
    espnId: 264,
    mascot: "Huskies",
    domain: "uw.edu",
  },
  {
    id: "wisconsin",
    name: "Wisconsin",
    abbr: "WIS",
    slug: "wisconsin",
    city: "Madison",
    state: "WI",
    primaryColor: "#C5050C",
    secondaryColor: "#FFFFFF",
    espnId: 275,
    mascot: "Badgers",
    domain: "wisc.edu",
  },
];

export const SPORTS: Sport[] = [
  {
    id: "football",
    name: "Football",
    slug: "football",
    icon: "🏈",
    gender: "Men",
    positions: ["QB", "RB", "WR", "TE", "OL", "DL", "LB", "DB", "K", "P"],
  },
  {
    id: "mens-basketball",
    name: "Men's Basketball",
    slug: "mens-basketball",
    icon: "🏀",
    gender: "Men",
    positions: ["PG", "SG", "SF", "PF", "C"],
  },
  {
    id: "womens-basketball",
    name: "Women's Basketball",
    slug: "womens-basketball",
    icon: "🏀",
    gender: "Women",
    positions: ["PG", "SG", "SF", "PF", "C"],
  },
  {
    id: "mens-track",
    name: "Men's Track & Field",
    slug: "mens-track",
    icon: "🏃",
    gender: "Men",
    positions: ["Sprints", "Distance", "Hurdles", "Jumps", "Throws", "Pole Vault", "Multi"],
  },
  {
    id: "womens-track",
    name: "Women's Track & Field",
    slug: "womens-track",
    icon: "🏃",
    gender: "Women",
    positions: ["Sprints", "Distance", "Hurdles", "Jumps", "Throws", "Pole Vault", "Multi"],
  },
  {
    id: "mens-soccer",
    name: "Men's Soccer",
    slug: "mens-soccer",
    icon: "⚽",
    gender: "Men",
    positions: ["GK", "DEF", "MID", "FWD"],
  },
  {
    id: "womens-soccer",
    name: "Women's Soccer",
    slug: "womens-soccer",
    icon: "⚽",
    gender: "Women",
    positions: ["GK", "DEF", "MID", "FWD"],
  },
  {
    id: "baseball",
    name: "Baseball",
    slug: "baseball",
    icon: "⚾",
    gender: "Men",
    positions: ["P", "C", "1B", "2B", "3B", "SS", "OF", "DH"],
  },
  {
    id: "softball",
    name: "Softball",
    slug: "softball",
    icon: "🥎",
    gender: "Women",
    positions: ["P", "C", "1B", "2B", "3B", "SS", "OF", "DP"],
  },
  {
    id: "wrestling",
    name: "Wrestling",
    slug: "wrestling",
    icon: "🤼",
    gender: "Men",
    positions: ["125", "133", "141", "149", "157", "165", "174", "184", "197", "285"],
  },
  {
    id: "mens-swimming",
    name: "Men's Swimming & Diving",
    slug: "mens-swimming",
    icon: "🏊",
    gender: "Men",
    positions: ["Freestyle", "Backstroke", "Breaststroke", "Butterfly", "IM", "Diving"],
  },
  {
    id: "womens-swimming",
    name: "Women's Swimming & Diving",
    slug: "womens-swimming",
    icon: "🏊",
    gender: "Women",
    positions: ["Freestyle", "Backstroke", "Breaststroke", "Butterfly", "IM", "Diving"],
  },
  {
    id: "mens-cross-country",
    name: "Men's Cross Country",
    slug: "mens-cross-country",
    icon: "🏃",
    gender: "Men",
    positions: ["Runner"],
  },
  {
    id: "womens-cross-country",
    name: "Women's Cross Country",
    slug: "womens-cross-country",
    icon: "🏃",
    gender: "Women",
    positions: ["Runner"],
  },
  {
    id: "volleyball",
    name: "Women's Volleyball",
    slug: "volleyball",
    icon: "🏐",
    gender: "Women",
    positions: ["S", "OH", "MB", "OPP", "L", "DS"],
  },
  {
    id: "mens-tennis",
    name: "Men's Tennis",
    slug: "mens-tennis",
    icon: "🎾",
    gender: "Men",
    positions: ["Singles", "Doubles"],
  },
  {
    id: "womens-tennis",
    name: "Women's Tennis",
    slug: "womens-tennis",
    icon: "🎾",
    gender: "Women",
    positions: ["Singles", "Doubles"],
  },
  {
    id: "mens-golf",
    name: "Men's Golf",
    slug: "mens-golf",
    icon: "⛳",
    gender: "Men",
    positions: ["Golfer"],
  },
  {
    id: "womens-golf",
    name: "Women's Golf",
    slug: "womens-golf",
    icon: "⛳",
    gender: "Women",
    positions: ["Golfer"],
  },
  {
    id: "womens-gymnastics",
    name: "Women's Gymnastics",
    slug: "womens-gymnastics",
    icon: "🤸",
    gender: "Women",
    positions: ["Vault", "Bars", "Beam", "Floor", "All-Around"],
  },
  {
    id: "mens-gymnastics",
    name: "Men's Gymnastics",
    slug: "mens-gymnastics",
    icon: "🤸",
    gender: "Men",
    positions: ["Floor", "Pommel", "Rings", "Vault", "Parallel Bars", "High Bar", "All-Around"],
  },
  {
    id: "mens-lacrosse",
    name: "Men's Lacrosse",
    slug: "mens-lacrosse",
    icon: "🥍",
    gender: "Men",
    positions: ["A", "M", "LSM", "D", "G"],
  },
  {
    id: "womens-lacrosse",
    name: "Women's Lacrosse",
    slug: "womens-lacrosse",
    icon: "🥍",
    gender: "Women",
    positions: ["A", "M", "D", "G"],
  },
  {
    id: "field-hockey",
    name: "Field Hockey",
    slug: "field-hockey",
    icon: "🏑",
    gender: "Women",
    positions: ["GK", "DEF", "MID", "FWD"],
  },
  {
    id: "rowing",
    name: "Women's Rowing",
    slug: "rowing",
    icon: "🚣",
    gender: "Women",
    positions: ["Coxswain", "Rower"],
  },
  {
    id: "mens-ice-hockey",
    name: "Men's Ice Hockey",
    slug: "mens-ice-hockey",
    icon: "🏒",
    gender: "Men",
    positions: ["G", "D", "LW", "C", "RW"],
  },
  {
    id: "womens-ice-hockey",
    name: "Women's Ice Hockey",
    slug: "womens-ice-hockey",
    icon: "🏒",
    gender: "Women",
    positions: ["G", "D", "LW", "C", "RW"],
  },
];

export const RATING_DIMENSIONS = [
  { key: "rating_coaching" as const, label: "Coaching", icon: "📋" },
  { key: "rating_culture" as const, label: "Culture", icon: "🤝" },
  { key: "rating_facilities" as const, label: "Facilities", icon: "🏟️" },
  { key: "rating_development" as const, label: "Development", icon: "📈" },
  { key: "rating_nil" as const, label: "NIL", icon: "💰" },
  { key: "rating_overall" as const, label: "Overall", icon: "⭐" },
];

export function getSchoolById(id: string): School | undefined {
  return BIG_TEN_SCHOOLS.find((s) => s.id === id || s.slug === id);
}

export function getSportById(id: string): Sport | undefined {
  return SPORTS.find((s) => s.id === id || s.slug === id);
}

export function getEspnLogoUrl(espnId: number): string {
  return `https://a.espncdn.com/i/teamlogos/ncaa/500/${espnId}.png`;
}

export function getContrastColor(hex: string): string {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  return luminance > 0.5 ? "#000000" : "#FFFFFF";
}
